name: Refresh event dates

on:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: production-event-refresh
  cancel-in-progress: false

jobs:
  deploy-production:
    if: vars.DEPLOYMENT_AUTHORITY == 'github'
    permissions:
      contents: read
      deployments: write
    uses: ./.github/workflows/deploy-production.yml
